### ISSUE TITLE
Works with 1.5 models, error with SDXL models or Turbo : "StableDiffusionPipeline.__init__() got an unexpected keyword argument 'text_encoder_2'"

### ISSUE THREAD

**Issue by antoineprobst** [Limitex/ComfyUI-Diffusers#8]
Hi !

Thank you for making this module.

I tried the second workflow, and it runs with SD 1.5 models, but when trying to load an SDXL model or Turbo it does this error :

![image](https://github.com/Limitex/ComfyUI-Diffusers/assets/101107079/42182b01-52a5-4bce-9593-f5c6bf951cc6)

**Comment by Limitex** [comment]
Thank you for the report. Since this repository supports Diffusers, it will support SDXL in the future.
However, StreamDiffusion's support for SDXL depends on the official repository.

**Comment by antoineprobst** [comment]
Thank you for your answer ! :)

**Comment by FeepingCreature** [comment]
Note that Diffusers now has SDXL support, so there could be nodes for it. I'm poking away at it, no luck so far.
